name: Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Atualizado para a versão v3

      - name: Build Docker image
        run: |
          docker build -t rsakis/container-technologies:v1.0.1 .


